### ISSUE TITLE
Dude,do u have any link of magicspells with minecraft 1.10-1.11?

### ISSUE THREAD

**Issue by SnUncle** [MidnightChipmunk/CrappyGameEngine#1]
I remember someone updated on the forum before

**Comment by maitmd** [comment]
1. I ask you not to submit issues to my projects if they are not related to my projects if you have any questions that do not pertain to the project please pm directly.

2. There is still an active community on Skype and MS is being updated by a different person.

[Skype](https://join.skype.com/fabCReeMCewK)
[Different Person](https://github.com/TheComputerGeek2/MagicSpells/releases)
